def print_analysis(result):
    print(f"\n TECHNICAL ANALYSIS RESULT FOR: {result['Ticker']}")
    print("="*80)
    print(f" Current Price: {result['Current Price']}")
    print(f" Trend: {result['Trend']}")
    print(f" Moving Averages: {result['MA Status']}")
    print(f" Ichimoku Cloud: {result['Ichimoku Signal']}")
    print(f" RSI (14): {result['RSI (14)']} – {result['RSI Signal']}")
    print(f" MACD: {result['MACD Signal']}")
    print(f" Stochastic: {result['Stochastic Signal']}")
    print(f" Volume: {result['Volume Signal']}")
    print(f" VWAP: {result['VWAP Signal']}")
    print(f" Volatility (ATR): {result['Volatility (ATR)']} ({result['Indicators Summary']['Volatility']})")
    print("\n Support/Resistance:")
    print(f" - Immediate Support: {result['Support Level']}")
    print(f" - Immediate Resistance: {result['Resistance Level']}")
    print(" - Fibonacci Levels:")
    for level, price in result['Fibonacci Levels'].items():
        print(f"   {level}: {round(price, 2)}")
    print(f"\n Potential Upside: {result['Potential Upside']}")
    print(f" Potential Downside: {result['Potential Downside']}")
    print(f" Risk/Reward Ratio: {result['Risk/Reward Ratio']}")
    print(f" Entry Range: {result['Entry Zone']}")
    print(f" Target 1: {result['Target 1']} | Target 2: {result['Target 2']} | Stop Loss: {result['Stop Loss']}")
    print("\n Indicators Summary:")
    print(f" - Trend Confirmation: {result['Indicators Summary']['Trend Confirmation']}")
    print(f" - Volume Confirmation: {result['Indicators Summary']['Volume Confirmation']}")
    print(f" - Volatility: {result['Indicators Summary']['Volatility']}")
    print("\n FUNDAMENTAL SNAPSHOT:")
    for key, val in result["Fundamental"].items():
        print(f" - {key}: {val}")
    print("\nDescription:")
    print(" - MA (Moving Averages): Used to smooth price data to identify the direction of the trend.")
    print(" - Ichimoku Cloud: Combines multiple indicators to show support, resistance, trend, and momentum.")
    print(" - RSI (Relative Strength Index): Measures the speed and change of price movements to identify overbought or oversold conditions.")
    print(" - MACD (Moving Average Convergence Divergence): Shows the relationship between two moving averages to indicate momentum.")
    print(" - Stochastic Oscillator: Compares a particular closing price to a range of its prices over a certain period to predict trend reversals.")
    print("   - %K: The fast line of the Stochastic Oscillator, measuring the position of the close relative to the price range.")
    print("   - %D: The slow line, a moving average of %K, used to smooth signals.")
    print(" - Volume: Analyzes the number of shares traded to confirm trends or potential reversals.")
    print(" - VWAP (Volume Weighted Average Price): Average price weighted by volume, used as a trading benchmark.")
    print(" - Volatility (ATR - Average True Range): Measures market volatility by analyzing recent trading ranges.")
    print(" - Fibonacci Levels: Key levels derived from the Fibonacci sequence used to predict potential support and resistance.")
    print(" - Support/Resistance: Key levels where price historically tends to reverse.")
    print(" - Risk/Reward Ratio: Estimates the potential reward of a trade relative to its risk.")
    print(" - OBV (On-Balance Volume): A volume-based indicator that measures buying and selling pressure.")
    print(" - Book Value per Share (BVPS): Represents the per-share value of a company's equity, calculated by dividing total shareholders' equity by shares outstanding.")
    print(" - Price to Book Value (PBV): A ratio used to compare a company's market value to its book value, indicating how much investors are willing to pay for each unit of net assets.")
    print(" - Trailing P/E: The Price-to-Earnings ratio based on the last 12 months of earnings. It shows how much investors are willing to pay for $1 of earnings.")
    print(" - Forward P/E: The Price-to-Earnings ratio based on forecasted earnings for the next 12 months, providing a forward-looking valuation metric.")
    print(" - EPS (TTM): Earnings Per Share for the trailing twelve months, indicating the company's profitability on a per-share basis.")
    print(" - Dividend Yield: The annual dividend income per share expressed as a percentage of the share price, reflecting the income potential of the stock.")
    print(" - Dividend per Share: The amount of money a company pays out to shareholders in the form of dividends per share.")
    print(" - Payout Ratio: The proportion of earnings paid out as dividends to shareholders, indicating how much of the company’s profit is distributed.")
    print(" - ROE: Return on Equity; a measure of financial performance, showing the profitability generated from shareholders' equity.")
    print(" - ROA: Return on Assets; indicates how efficiently a company uses its assets to generate profit.")
    print(" - Debt to Equity: The ratio of a company's total debt to its shareholders' equity, showing the degree to which a company is financing its operations through debt.")
    print(" - Current Ratio: A liquidity ratio that measures a company's ability to pay short-term obligations with its current assets.")
    print(" - Quick Ratio: A more stringent measure of liquidity, excluding inventory from current assets to evaluate the company’s ability to cover short-term obligations.")
    print(" - Gross Margin: The percentage of revenue left after deducting the cost of goods sold, showing the efficiency of production and sales processes.")
    print(" - Operating Margin: The percentage of revenue remaining after covering operating expenses, indicating operational efficiency.")
    print(" - Profit Margin: The percentage of revenue remaining after all expenses, taxes, and costs, reflecting the overall profitability of the company.")
    print(" - Revenue (TTM): The total amount of money generated from sales over the trailing twelve months.")
    print(" - Net Income (TTM): The company’s total profit after expenses, taxes, and other costs for the trailing twelve months.")
    print(" - Free Cash Flow: The cash generated by the business that is available to be used for expansion, dividends, or debt reduction.")
    print(" - Beta: A measure of a stock’s volatility in relation to the overall market. (N/A means no data available).")
    print(" - 52 Week High: The highest stock price reached in the past 52 weeks, reflecting the stock's maximum value in the recent year.")
    print(" - 52 Week Low: The lowest stock price reached in the past 52 weeks, reflecting the stock's minimum value in the recent year.")
    print(" - Trailing Annual Net Income: The total net income for the last 12 months, showing the company’s overall profitability.")
    print(" - Operating Cash Flow: The cash generated by a company’s regular business activities, indicating its ability to generate cash from operations.")
    print(" - Shares Outstanding: The total number of shares that are currently owned by shareholders, which impacts stock value and liquidity.")
    print(" - Total Assets: The total value of everything the company owns, including both current and long-term assets, indicating the company’s size and financial strength.")
    print("="*80)